### ISSUE TITLE
Support for icons?

### ISSUE THREAD

**Issue by alfg** [alfg/mumble-widget#7]
From an email:

> I was wondering if there is any way to add icons (muted deafened etc.) to the display?

Maybe adding a sprite or lightweight icon library to add icons to the widget.

**Comment by HarpyWar** [comment]
It may looks better with icons instead of a dash before a nickname.

**Comment by alfg** [comment]
I've exposed some css classes that are mapped to the user data from the CVP for when the property is true. 

```
mute: .mute-on
deaf: .deaf-on
selfDeaf: .self-deaf-on
selfMute: .self-mute-on
prioritySpeaker: .priority-speaker-on
recording: .recording-on
```

Here's an example:
http://jsfiddle.net/s0kszLq9/2/

These aren't live yet, so using the following resource:
http://jsfiddle.net/s0kszLq9/2/

**Comment by alfg** [comment]
CDN updated and published.

https://github.com/alfg/mumble-widget/pull/8
